# Generated by Django 4.2.11 on 2024-05-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('author', models.CharField(max_length=150, verbose_name='نام نویسنده')),
                ('content', models.TextField(verbose_name='محتوای پست')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='زمان ایجاد پست')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ویرایش پست')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر شاخص')),
                ('emailAddress', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('interested', models.BooleanField(default=False, verbose_name='پسند شده')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت نمایش')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پستها',
            },
        ),
    ]
